---

- name: Enable and start spamd
  lineinfile: dest="/etc/rc.conf" regexp="^spamd_enable" line="spamd_enable=\"{{ spamd_enable }}\"" backup="yes"
  notify: enable and start spamd
  when: spamd_enable == "YES"
  tags: config_rc_conf_spamd

- name: Disable and stop spamd
  lineinfile: dest="/etc/rc.conf" regexp="^spamd_enable" line="spamd_enable=\"{{ spamd_enable }}\"" backup="yes"
  notify: disable and stop spamd
  when: spamd_enable == "NO"
  tags: config_rc_conf_spamd

- name: Configure spamd
  lineinfile: dest="/etc/rc.conf" regexp="{{ item.regexp }}" line="{{ item.line }}" backup="yes"
  with_items:
    - { regexp: "^spamd_flags", line: "spamd_flags=\"{{ spamd_flags }}\""}
  notify: restart splamd
  tags: config_rc_conf_spamd
