---

- name: Configure spamfilter  {{postfix_master_cf}}
  lineinfile: dest={{postfix_master_cf}} regexp="^spamfilter\\s*unix " line="spamfilter unix  -       n       n       -       -       pipe" backup="yes"
  notify: reload postfix
  tags:
    - config_potfix_master_cf_spamfilter

- name: Configure spamfilter options {{postfix_master_cf}}
  lineinfile: dest={{postfix_master_cf}} regexp="{{ item.regexp }}" line="{{ item.line }}" insertafter="^spamfilter unix " backup="yes"
  with_items:
    - { regexp: "\\s*flags=Rq user=spamd argv=/usr/bin/spamfilter.sh", line: "   flags=Rq user=spamd argv=/usr/bin/spamfilter.sh -oi -f ${sender} ${recipient}"}
  notify: reload postfix
  tags:
    - config_potfix_master_cf_spamfilter

- name: Configure smtp {{postfix_master_cf}}
  lineinfile: dest={{postfix_master_cf}} regexp="^smtp\\s*inet " line="smtp  {{postfix_master_cf_service_def}}" backup="yes"
  notify: reload postfix
  tags:
    - config_potfix_master_cf_smtp

- name: Configure smtps {{postfix_master_cf}}
  lineinfile: dest={{postfix_master_cf}} regexp="^smtps\\s*inet " line="smtps  {{postfix_master_cf_service_def}}" backup="yes"
  notify: reload postfix
  tags:
    - config_potfix_master_cf_smtps

- name: Configure submission {{postfix_master_cf}}
  lineinfile: dest={{postfix_master_cf}} regexp="^submission\\s*inet " line="submission  {{postfix_master_cf_service_def}}" backup="yes"
  notify: reload postfix
  tags:
    - config_potfix_master_cf_submission
