---

- name: "copy_spamfilter: Copy spamfilter.sh to /usr/bin"
  copy:
    src: "{{ role_path }}/files/spamfilter.sh"
    dest: "/usr/bin/spamfilter.sh"
    owner: "root"
    group: "wheel"
    mode: "0755"

# EOF
...
