---
- name: Debug
  vars:
    msg: |-
      fm_sa_role_version {{ fm_sa_role_version }}
      ansible_architecture: {{ ansible_architecture }}
      ansible_os_family: {{ ansible_os_family }}
      ansible_distribution: {{ ansible_distribution }}
      ansible_distribution_major_version: {{ ansible_distribution_major_version }}
      ansible_distribution_version: {{ ansible_distribution_version }}
      ansible_distribution_release: {{ ansible_distribution_release }}
      ansible_python_version: {{ ansible_python_version }}

      fm_sa_sanity: {{ fm_sa_sanity }}
      fm_sa_sanity_platform: {{ fm_sa_sanity_platform }}
      fm_sa_sanity_ansible_version: {{ fm_sa_sanity_ansible_version }}
      fm_sa_sanity_packages: {{ fm_sa_sanity_packages }}
      al_debug: {{ al_debug }}
      al_sanity_packages_required:
        {{ al_sanity_packages_required | to_yaml(indent=2) | indent(2) }}
      fm_sa_install: {{ fm_sa_install }}
      freebsd_install_method: {{ freebsd_install_method }}
      freebsd_use_packages: {{ freebsd_use_packages }}
      fm_sa_packages:
        {{ fm_sa_packages | to_nice_yaml(indent=2) | indent(2) }}
      fm_sa_spamd_enable: {{ fm_sa_spamd_enable }}
      fm_sa_spamd_flags: {{ fm_sa_spamd_flags }}
      fm_sa_spamd_rcconf:
        {{ fm_sa_spamd_rcconf | to_yaml(indent=2) | indent(2) }}
      fm_sa_periodic_conf:
        {{ fm_sa_periodic_conf | to_yaml(indent=2) | indent(2) }}
      fm_sa_spamfilter_path: {{ fm_sa_spamfilter_path }}
      postfix_master_cf: {{ postfix_master_cf }}
      postfix_master_cf_service_def: {{ postfix_master_cf_service_def }}

  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

# EOF
