---

- name: "freebsd-mailserver-spamassassin Debug"
  vars:
    msg: |
         ansible_architecture [ {{ ansible_architecture }} ]
         ansible_os_family [ {{ ansible_os_family }} ]
         ansible_distribution [ {{ ansible_distribution }} ]
         ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
         ansible_distribution_version [ {{ ansible_distribution_version }} ]
         ansible_distribution_release [ {{ ansible_distribution_release }} ]

         freebsd_install_method [ {{ freebsd_install_method }} ]
         freebsd_use_packages [ {{ freebsd_use_packages }} ]
         fm_sa_packages
         {{ fm_sa_packages | to_nice_yaml }}
         fm_sa_spamd_enable [ {{ fm_sa_spamd_enable }} ]
         fm_sa_spamd_flags [ {{ fm_sa_spamd_flags }} ]
         fm_sa_periodic_conf
         {{ fm_sa_periodic_conf | to_yaml }}
         fm_sa_spamfilter_path [ {{ fm_sa_spamfilter_path }} ]
         postfix_master_cf [ {{ postfix_master_cf }} ]
         postfix_master_cf_service_def [ {{ postfix_master_cf_service_def }} ]

  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
