---

- name: "Debug"
  vars:
    msg: |-
         ansible_architecture [{{ ansible_architecture }}]
         ansible_os_family [{{ ansible_os_family }}]
         ansible_distribution [{{ ansible_distribution }}]
         ansible_distribution_major_version [{{ ansible_distribution_major_version }}]
         ansible_distribution_version [{{ ansible_distribution_version }}]
         ansible_distribution_release [{{ ansible_distribution_release }}]
         ansible_python_version [{{ ansible_python_version }}]

         fm_sa_sanity [{{ fm_sa_sanity }}]
         fm_sa_sanity_platform [{{ fm_sa_sanity_platform }}]
         fm_sa_sanity_ansible_version [{{ fm_sa_sanity_ansible_version }}]
         fm_sa_sanity_packages [{{ fm_sa_sanity_packages }}]
         al_sanity_packages_required
         {{ al_sanity_packages_required|to_yaml }}

         fm_sa_install [{{ fm_sa_install }}]
         freebsd_install_method [{{ freebsd_install_method }}]
         freebsd_use_packages [{{ freebsd_use_packages }}]
         fm_sa_packages
         {{ fm_sa_packages|to_nice_yaml }}

         fm_sa_spamd_enable [{{ fm_sa_spamd_enable }}]
         fm_sa_spamd_flags [{{ fm_sa_spamd_flags }}]
         fm_sa_periodic_conf
         {{ fm_sa_periodic_conf|to_yaml }}
         fm_sa_spamfilter_path [{{ fm_sa_spamfilter_path }}]
         postfix_master_cf [{{ postfix_master_cf }}]
         postfix_master_cf_service_def [{{ postfix_master_cf_service_def }}]

         al_debug [{{ al_debug }}]
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
