---
# tasks for freebsd-mailserver-spamassassin

- import_tasks: debug.yml
  when: fm_sa_debug
  tags: fm-sa-debug

- import_tasks: packages.yml
  tags: fm-sa-packages

- import_tasks: rcconf.yml
  tags: fm-sa-rcconf

- import_tasks: postfix_master.yml
  tags: fm-sa-postfix_master

- import_tasks: copy_spamfilter.yml
  tags: fm-sa-copy_spamfilter

- import_tasks: periodic_conf.yml
  tags: fm-sa-periodic_conf

# EOF
...
