---
- name: "Periodic_conf: Configure /etc/periodic.conf.local"
  ansible.builtin.lineinfile:
    dest: /etc/periodic.conf.local
    regexp: ^\s*{{ item.regexp }}\s*=(.*)$
    line: '{{ item.regexp }}="{{ item.value }}"'
    backup: "{{ fm_sa_backup_conf }}"
    create: true
    mode: "0644"
  loop: "{{ fm_sa_periodic_conf }}"

# EOF
