---

- name: "periodic_conf: Configure /etc/periodic.conf.local"
  lineinfile:
    dest: "/etc/periodic.conf.local"
    regexp: "^\\s*{{ item.regexp }}\\s*="
    line: "{{ item.regexp }}=\"{{ item.value }}\""
    backup: "{{ fm_sa_backup_conf }}"
    create: true
  loop: "{{ fm_sa_periodic_conf }}"

# EOF
...
