---
- name: "Sanity: Get meta-data and role_name."
  when: fm_sa_sanity_platform|bool or fm_sa_sanity_ansible_version|bool
  block:

    - name: "Sanity: Get meta-data."
      ansible.builtin.include_vars:
        file: meta/main.yml
      when: galaxy_info is undefined

    - name: "Sanity: Get role_name."
      ansible.builtin.set_fact:
        al_sanity_role_name: "{{ role_name }}"

- name: "Sanity: Test supported platform."
  when: fm_sa_sanity_platform | bool
  block:

    - name: "Sanity: Instantiate variable al_supported_versions_override"
      ansible.builtin.set_fact:
        al_supported_versions_override: "{{ al_supported_versions_override }}"
        al_sanity_platform_warning: "{{ al_sanity_platform_warning }}"

    - name: "Sanity: Include vbotka.ansible_lib al_sanity_platform."
      ansible.builtin.include_role:
        name: vbotka.ansible_lib
        tasks_from: al_sanity_platform

- name: "Sanity: Include vbotka.ansible_lib al_sanity_ansible_version."
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_sanity_ansible_version
  when: fm_sa_sanity_ansible_version | bool

- name: "Sanity: Include vbotka.ansible_lib al_sanity_packages."
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_sanity_packages
  when: fm_sa_sanity_packages | bool

# EOF
