---
# handlers for freebsd_mailserver_spamassassin

  # sa-spamd
- name: Update spamd rules
  listen: update spamd rules
  ansible.builtin.command:
    cmd: /usr/local/bin/sa-update
  register: out
  changed_when: out.rc == 0 # update downloaded and installed; 1 no update available
  failed_when: out.rc >= 2  # update failed

- name: Enable and start spamd
  listen: enable and start spamd
  ansible.builtin.service:
    name: sa-spamd
    state: started
    enabled: true

- name: Disable and stop spamd
  listen: disable and stop spamd
  ansible.builtin.service:
    name: sa-spamd
    state: stopped
    enabled: false

- name: Restart spamd
  listen: restart spamd
  ansible.builtin.service:
    name: sa-spamd
    state: restarted
  when: fm_sa_spamd_enable | bool

- name: Reload spamd
  listen: reload spamd
  ansible.builtin.service:
    name: sa-spamd
    state: reloaded
  when: fm_sa_spamd_enable | bool

  # postfix
- name: Postfix check # noqa: no-changed-when
  listen: postfix check
  ansible.builtin.command:
    cmd: /usr/local/sbin/postfix check

- name: Reload postfix
  listen: reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: Restart postfix
  listen: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

# EOF
